services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./api:/api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
  front:
    build:
      context: ./front
    volumes:
      - ./front/app:/front
    command: 'yarn start'
    ports:
      - 3000:3000
volumes:
  mysql-data:
