services:
  db:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  postgresql-data:
